"""HTML report generation for polished presentation.

Provides HTML-formatted reports with embedded CSS for professional
presentation and easy sharing.
"""

from datetime import datetime
from typing import Any, Optional

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jenkins Security Assessment Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            background-color: white;
            padding: 40px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            border-radius: 8px;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            border-left: 4px solid #3498db;
            padding-left: 15px;
        }}
        h3 {{
            color: #7f8c8d;
            margin-top: 20px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: white;
        }}
        th {{
            background-color: #34495e;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }}
        td {{
            padding: 10px 12px;
            border-bottom: 1px solid #ecf0f1;
        }}
        tr:hover {{
            background-color: #f8f9fa;
        }}
        .severity-critical {{
            color: #e74c3c;
            font-weight: bold;
        }}
        .severity-high {{
            color: #e67e22;
            font-weight: bold;
        }}
        .severity-medium {{
            color: #f39c12;
            font-weight: bold;
        }}
        .severity-low {{
            color: #3498db;
            font-weight: bold;
        }}
        .stat-box {{
            display: inline-block;
            margin: 10px;
            padding: 20px;
            background-color: #ecf0f1;
            border-radius: 5px;
            min-width: 150px;
            text-align: center;
        }}
        .stat-number {{
            font-size: 2em;
            font-weight: bold;
            color: #3498db;
        }}
        .stat-label {{
            color: #7f8c8d;
            font-size: 0.9em;
        }}
        .info-box {{
            background-color: #d1ecf1;
            border-left: 4px solid #0c5460;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        .warning-box {{
            background-color: #fff3cd;
            border-left: 4px solid #856404;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        .danger-box {{
            background-color: #f8d7da;
            border-left: 4px solid #721c24;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        .recommendation {{
            padding: 10px;
            margin: 10px 0;
            background-color: #e8f5e9;
            border-left: 3px solid #4caf50;
            border-radius: 3px;
        }}
        .vuln-details {{
            background-color: #f8f9fa;
            padding: 15px;
            margin: 10px 0;
            border-radius: 5px;
            border: 1px solid #dee2e6;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ecf0f1;
            text-align: center;
            color: #7f8c8d;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
{content}
        <div class="footer">
            <p>Report generated by JenkinsBreaker on {timestamp}</p>
        </div>
    </div>
</body>
</html>
"""


class HTMLReporter:
    """Generates HTML reports for exploitation findings."""

    def __init__(self):
        """Initialize HTML reporter."""
        self.findings: list[dict[str, Any]] = []
        self.credentials: list[dict[str, Any]] = []
        self.vulnerabilities: list[dict[str, Any]] = []
        self.persistence: list[dict[str, Any]] = []
        self.lateral_movement: list[dict[str, Any]] = []

    def add_finding(
        self,
        category: str,
        severity: str,
        title: str,
        description: str,
        details: Optional[dict[str, Any]] = None
    ) -> None:
        """Add a finding to the report."""
        self.findings.append({
            "category": category,
            "severity": severity,
            "title": title,
            "description": description,
            "details": details or {}
        })

    def add_vulnerability(
        self,
        cve_id: str,
        name: str,
        severity: str,
        status: str,
        details: Optional[dict[str, Any]] = None
    ) -> None:
        """Add vulnerability to report."""
        self.vulnerabilities.append({
            "cve_id": cve_id,
            "name": name,
            "severity": severity,
            "status": status,
            "details": details or {}
        })

    def add_credential(
        self,
        credential_type: str,
        source: str,
        username: Optional[str] = None,
        details: Optional[dict[str, Any]] = None
    ) -> None:
        """Add credential to report."""
        self.credentials.append({
            "type": credential_type,
            "source": source,
            "username": username,
            "details": details or {}
        })

    def add_persistence(
        self,
        method: str,
        status: str,
        details: Optional[dict[str, Any]] = None
    ) -> None:
        """Add persistence mechanism to report."""
        self.persistence.append({
            "method": method,
            "status": status,
            "details": details or {}
        })

    def add_lateral_movement(
        self,
        target: str,
        method: str,
        status: str,
        details: Optional[dict[str, Any]] = None
    ) -> None:
        """Add lateral movement attempt to report."""
        self.lateral_movement.append({
            "target": target,
            "method": method,
            "status": status,
            "details": details or {}
        })

    def _generate_header(self, target: str, jenkins_version: Optional[str]) -> str:
        """Generate report header."""
        html = "<h1>Jenkins Security Assessment Report</h1>\n"

        html += '<div class="info-box">\n'
        html += f"<strong>Target:</strong> {target}<br>\n"

        if jenkins_version:
            html += f"<strong>Jenkins Version:</strong> {jenkins_version}<br>\n"

        html += f"<strong>Assessment Date:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
        html += "</div>\n"

        return html

    def _generate_statistics(self) -> str:
        """Generate statistics section."""
        critical_vulns = sum(1 for v in self.vulnerabilities if v["severity"].lower() == "critical")
        high_vulns = sum(1 for v in self.vulnerabilities if v["severity"].lower() == "high")

        html = "<h2>Executive Summary</h2>\n"
        html += '<div style="text-align: center;">\n'

        html += '<div class="stat-box">\n'
        html += f'<div class="stat-number">{len(self.vulnerabilities)}</div>\n'
        html += '<div class="stat-label">Vulnerabilities</div>\n'
        html += "</div>\n"

        html += '<div class="stat-box">\n'
        html += f'<div class="stat-number" style="color: #e74c3c;">{critical_vulns}</div>\n'
        html += '<div class="stat-label">Critical</div>\n'
        html += "</div>\n"

        html += '<div class="stat-box">\n'
        html += f'<div class="stat-number" style="color: #e67e22;">{high_vulns}</div>\n'
        html += '<div class="stat-label">High Severity</div>\n'
        html += "</div>\n"

        html += '<div class="stat-box">\n'
        html += f'<div class="stat-number">{len(self.credentials)}</div>\n'
        html += '<div class="stat-label">Credentials</div>\n'
        html += "</div>\n"

        html += '<div class="stat-box">\n'
        html += f'<div class="stat-number">{len(self.persistence)}</div>\n'
        html += '<div class="stat-label">Persistence</div>\n'
        html += "</div>\n"

        html += "</div>\n"

        if critical_vulns > 0:
            html += '<div class="danger-box">\n'
            html += f"<strong>CRITICAL:</strong> {critical_vulns} critical severity vulnerabilities detected. Immediate action required.\n"
            html += "</div>\n"

        return html

    def _generate_vulnerabilities_section(self) -> str:
        """Generate vulnerabilities section."""
        if not self.vulnerabilities:
            return ""

        html = "<h2>Identified Vulnerabilities</h2>\n"
        html += "<table>\n"
        html += "<tr><th>CVE ID</th><th>Name</th><th>Severity</th><th>Status</th></tr>\n"

        for vuln in sorted(self.vulnerabilities, key=lambda x: x["severity"], reverse=True):
            severity_class = f"severity-{vuln['severity'].lower()}"
            html += f"<tr><td>{vuln['cve_id']}</td><td>{vuln['name']}</td>"
            html += f"<td class='{severity_class}'>{vuln['severity'].upper()}</td>"
            html += f"<td>{vuln['status']}</td></tr>\n"

        html += "</table>\n"

        html += "<h3>Vulnerability Details</h3>\n"

        for vuln in self.vulnerabilities:
            html += '<div class="vuln-details">\n'
            html += f"<h4>{vuln['cve_id']}: {vuln['name']}</h4>\n"
            html += f"<p><strong>Severity:</strong> <span class='severity-{vuln['severity'].lower()}'>{vuln['severity'].upper()}</span></p>\n"
            html += f"<p><strong>Status:</strong> {vuln['status']}</p>\n"

            if vuln.get("details"):
                html += "<p><strong>Details:</strong></p><ul>\n"
                for key, value in vuln["details"].items():
                    html += f"<li><strong>{key}:</strong> {value}</li>\n"
                html += "</ul>\n"

            html += "</div>\n"

        return html

    def _generate_credentials_section(self) -> str:
        """Generate credentials section."""
        if not self.credentials:
            return ""

        html = "<h2>Extracted Credentials</h2>\n"
        html += '<div class="warning-box">\n'
        html += "<strong>WARNING:</strong> Credentials have been extracted. Immediate rotation required.\n"
        html += "</div>\n"

        html += "<table>\n"
        html += "<tr><th>Type</th><th>Source</th><th>Username</th></tr>\n"

        for cred in self.credentials:
            username = cred.get("username", "N/A")
            html += f"<tr><td>{cred['type']}</td><td>{cred['source']}</td><td>{username}</td></tr>\n"

        html += "</table>\n"

        return html

    def _generate_recommendations_section(self) -> str:
        """Generate recommendations section."""
        html = "<h2>Recommendations</h2>\n"

        recommendations = []

        if self.vulnerabilities:
            recommendations.append("Update Jenkins to the latest version to patch identified vulnerabilities")

        if any(v.get("severity") == "critical" for v in self.vulnerabilities):
            recommendations.append("Immediately patch critical vulnerabilities")

        if self.credentials:
            recommendations.append("Rotate all exposed credentials immediately")
            recommendations.append("Implement secrets management solution")

        if self.persistence:
            recommendations.append("Audit system for unauthorized persistence mechanisms")

        if self.lateral_movement:
            recommendations.append("Implement network segmentation")

        recommendations.extend([
            "Enable audit logging and monitoring",
            "Implement principle of least privilege",
            "Regular security assessments",
            "Deploy security hardening configurations"
        ])

        for i, rec in enumerate(recommendations, 1):
            html += f'<div class="recommendation">{i}. {rec}</div>\n'

        return html

    def generate(
        self,
        target: str,
        jenkins_version: Optional[str] = None
    ) -> str:
        """Generate HTML report.

        Args:
            target: Target Jenkins URL
            jenkins_version: Jenkins version

        Returns:
            HTML report string
        """
        content = self._generate_header(target, jenkins_version)
        content += self._generate_statistics()
        content += self._generate_vulnerabilities_section()
        content += self._generate_credentials_section()
        content += self._generate_recommendations_section()

        timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')

        return HTML_TEMPLATE.format(content=content, timestamp=timestamp)

    def save(
        self,
        filename: str,
        target: str,
        jenkins_version: Optional[str] = None
    ) -> None:
        """Save HTML report to file.

        Args:
            filename: Output filename
            target: Target Jenkins URL
            jenkins_version: Jenkins version
        """
        report_html = self.generate(target, jenkins_version)

        with open(filename, 'w') as f:
            f.write(report_html)


def create_html_report(
    target: str,
    findings: Optional[list[dict[str, Any]]] = None,
    credentials: Optional[list[dict[str, Any]]] = None,
    vulnerabilities: Optional[list[dict[str, Any]]] = None,
    jenkins_version: Optional[str] = None
) -> str:
    """Factory function to create HTML report.

    Args:
        target: Target Jenkins URL
        findings: Optional list of findings
        credentials: Optional list of credentials
        vulnerabilities: Optional list of vulnerabilities
        jenkins_version: Optional Jenkins version

    Returns:
        HTML report string
    """
    reporter = HTMLReporter()

    if findings:
        for finding in findings:
            reporter.add_finding(**finding)

    if credentials:
        for cred in credentials:
            reporter.add_credential(**cred)

    if vulnerabilities:
        for vuln in vulnerabilities:
            reporter.add_vulnerability(**vuln)

    return reporter.generate(target, jenkins_version)
